name: grpg_streaming
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  grpc: ^3.2.3
  dotenv: ^4.1.0
  dbcrypt: ^2.0.0
  jose: ^0.3.4
  protobuf: ^3.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0

