name: grpg_streaming
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  inno_database:
    git:
      url: https://github.com/innoapps-dev/innoapps
      path: packages/inno_database

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0

dependency_overrides:
  postgres:
    git:
      url: https://github.com/isoos/postgresql-dart